In [2]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
from sklearn.model_selection import train_test_split as tts
train, test = tts(df, test_size = 0.2)

In [5]:
xtrain = train.loc[:, train.columns != 'species']
xtest = test.loc[:, test.columns != 'species']

ytrain = train['species']
ytest = test['species']

In [6]:
from sklearn.svm import SVC
model = SVC(kernel = 'poly', degree = 8)
model.fit(xtrain, ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
ypred= model.predict(xtest)

In [8]:
result = pd.DataFrame({'actual':ytest, 'predicted':ypred})
print(result)

         actual   predicted
52   versicolor  versicolor
5        setosa      setosa
104   virginica   virginica
50   versicolor  versicolor
27       setosa      setosa
88   versicolor  versicolor
95   versicolor  versicolor
82   versicolor  versicolor
118   virginica  versicolor
47       setosa      setosa
131   virginica  versicolor
22       setosa      setosa
64   versicolor  versicolor
136   virginica   virginica
108   virginica   virginica
107   virginica   virginica
2        setosa      setosa
134   virginica   virginica
28       setosa      setosa
128   virginica   virginica
33       setosa      setosa
4        setosa      setosa
36       setosa      setosa
140   virginica   virginica
149   virginica   virginica
25       setosa      setosa
77   versicolor  versicolor
126   virginica   virginica
46       setosa      setosa
21       setosa      setosa


In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytest, ypred))

[[12  0  0]
 [ 0  7  0]
 [ 0  2  9]]


In [10]:
print(classification_report(ytest, ypred))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        12
 versicolor       0.78      1.00      0.88         7
  virginica       1.00      0.82      0.90        11

avg / total       0.95      0.93      0.93        30

