In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('bill_authentication.csv')
df.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [3]:
from sklearn.model_selection import train_test_split as tts
train, test = tts(df, test_size = 0.2)

In [4]:
train_x = train.loc[:, train.columns != 'Class']
test_x = test.loc[:, test.columns != 'Class']

train_y = train['Class']
test_y = test['Class']

In [5]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(train_x, train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [6]:
pred_y = model.predict(test_x)

In [8]:
result = pd.DataFrame({'Actual': test_y, 'Predicted':pred_y})
print(result)

      Actual  Predicted
1084       1          1
1151       1          1
957        1          1
1172       1          1
312        0          0
643        0          0
574        0          0
1043       1          1
152        0          0
1126       1          1
1305       1          1
402        0          0
1045       1          1
36         0          0
341        0          0
911        1          0
399        0          0
1296       1          1
1301       1          1
1190       1          1
1235       1          1
1267       1          1
1150       1          1
1255       1          1
566        0          0
387        0          0
704        0          0
439        0          0
471        0          0
641        0          0
...      ...        ...
404        0          0
774        1          1
281        0          0
1095       1          1
644        0          0
1135       1          1
1143       1          1
6          0          0
778        1          1
912        1    

In [12]:
from sklearn.metrics import confusion_matrix as cm, classification_report as cr
print(cm(test_y, pred_y))
print(cr(test_y, pred_y))

[[152   2]
 [  1 120]]
             precision    recall  f1-score   support

          0       0.99      0.99      0.99       154
          1       0.98      0.99      0.99       121

avg / total       0.99      0.99      0.99       275



In [13]:
data = sns.load_dataset('iris')
print(data.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [14]:
train, test = tts(data, test_size = 0.2)
train_x = train.loc[:, train.columns != 'species']
test_x = test.loc[:, test.columns != 'species']

train_y = train['species']
test_y = test['species']

In [16]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs = 2)
clf.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [17]:
pred_y = clf.predict(test_x)

In [18]:
result = pd.DataFrame({'Actual': test_y, 'Predicted':pred_y})
print(result)

         Actual   Predicted
91   versicolor  versicolor
52   versicolor  versicolor
61   versicolor  versicolor
114   virginica   virginica
141   virginica   virginica
41       setosa      setosa
85   versicolor  versicolor
67   versicolor  versicolor
56   versicolor  versicolor
64   versicolor  versicolor
23       setosa      setosa
104   virginica   virginica
57   versicolor  versicolor
17       setosa      setosa
108   virginica   virginica
42       setosa      setosa
147   virginica   virginica
118   virginica   virginica
84   versicolor  versicolor
4        setosa      setosa
128   virginica   virginica
21       setosa      setosa
111   virginica   virginica
33       setosa      setosa
145   virginica   virginica
36       setosa      setosa
78   versicolor  versicolor
30       setosa      setosa
115   virginica   virginica
58   versicolor  versicolor


In [19]:
from sklearn.metrics import confusion_matrix as cm, classification_report as cr
print(cm(test_y, pred_y))
print(cr(test_y, pred_y))

[[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00         9
 versicolor       1.00      1.00      1.00        11
  virginica       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        30

